config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles
  devise_for :users
  get "search", to: "search#search"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/saved_search.rb
class SavedSearch < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :saved_searches, dependent: :destroy

  def saved_search_exist?(search_data)
    self.saved_searches.where(search_params: search_data).present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protected

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :show, :new, :create, :update]
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @articles = Article.where("lower(title) like ?", "%#{params[:query].downcase}%")
    if should_save?
      SavedSearch.create(user_id: current_user.id, search_params: params[:query].downcase) unless current_user.saved_search_exist?(params[:query].downcase)
    end
    
    respond_to do |format| 
      format.js { render :search }
    end
  end

  private

  def should_save?
    ActiveModel::Type::Boolean.new.cast(params[:save]) && params[:query].length > 3 && current_user.present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_article_list.erb
<% @articles.each do |article| %>
  <div class="border-bottom-one p-3">
    <p class="article-list-title"><%= article.title %></p>
    <%= link_to 'details', article, class: "genereal-btn-styles" %>
  </div>
<% end %>

app/views/articles/_form.html.erb
<div class="row">
  <div class="col-md-5 mx-auto">
    <%= form_with(model: article) do |form| %>
      <% if article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>
          <ul>
            <% article.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="field">
        <%= form.label :title %>
        <%= form.text_field :title, class: "form-control" %>
      </div>
      <div class="field">
        <%= form.label :content %>
        <%= form.text_field :content, class: "form-control" %>
      </div>
      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/articles/_saved_searches.html.erb
<% if user_signed_in? %>
  <% current_user.saved_searches.order(created_at: :desc).each do |saved_search| %>
    <p class="saved-search"><%= saved_search.search_params %></p>
  <% end %>
<% else %>
  <div>
    <%= link_to "Sign In to save your searches", new_user_session_path, class: "genereal-btn-styles" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3 class="text-center">Editing Article</h3>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
  <%= render "search/search_form" %>

  <div>
    <div class="row">
      <div class="col-md-8">
        <h2>Articles</h2>
        <div class="article-list">
          <%= render "articles/article_list"%>
        </div>
      </div>
      <div class="col-md-4">
        <h2 class="text-center">Saved Searches</h2>
        <div class="saved-searches">
          <%= render "articles/saved_searches" %>
        </div>
      </div>
    </div>
  </div>

  <br>
  <%= link_to 'New Article', new_article_path, class: "genereal-btn-styles" %>
</div>

app/views/articles/new.html.erb
<h3 class="text-center">New Article</h3>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<div class="container-fluid">
  <h3 class="text-center"><%= @article.title %></h3>
  <div class="text-center my-5">
    <%= @article.content %>
  </div>
  <div>
    <%= link_to 'Edit', edit_article_path(@article), class: "genereal-btn-styles" %> |
    <%= link_to 'Back', articles_path, class: "genereal-btn-styles" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SearchArticles</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render "shared/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/search/_search_form.html.erb
<div class="row search-form-div mt-3 mb-5">
    <div class="col-md-4 mx-auto">
      <%= form_with url: search_path, method: :get, remote: false, html: {id: "search-form"} do |form| %>
        <div class="row field-wrapper">
          <div class="col-md-11">
            <%= form.text_field :query, placeholder: "Enter your search", class: "form-control" %>
          </div>
          <div class="col-md-1">
            <i class="fa-solid fa-magnifying-glass"></i>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/search/search.js.erb
$(".article-list").html('<%=  escape_javascript(render :partial => "articles/article_list") %>')
$(".saved-searches").html('<%=  escape_javascript(render :partial => "articles/saved_searches") %>')

app/views/shared/_navbar.html.erb
<nav class="d-flex justify-content-between align-items-center">
  <div><%= link_to "Search", root_path, class: "navbar-branding" %></div>
  <div>
    <% if user_signed_in? %>
      <%= link_to current_user.email, root_path, class: "navbar-links" %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "navbar-sign-links" %>
    <% else %>
      <%= link_to "Sign In", new_user_session_path, class: "navbar-links" %>
    <% end %>
  </div>
</nav>